import { invoke } from '@tauri-apps/api/core';

import { integer } from './format';
import { errorCode, errorDetailNumber, errorMessage, errorText } from './messages';
import { notifyError } from '../stores/notices';
import type { Alert } from '../stores/alerts';

/**
 * What the user sees when a file they chose cannot be opened, or opens in a way they should
 * know about. Built here and shown by the project store, which owns the retry.
 */

/** Failures that mean "this is not a sliced print", as opposed to "this print is damaged". */
const NOT_GCODE = new Set(['model_file', 'no_gcode_in_archive', 'unsupported_container']);

export function openFailureAlert(
  path: string,
  e: unknown,
  actions: { retry: () => void | Promise<void>; pickAnother: () => void | Promise<void> },
): Alert {
  const name = nameOf(path);
  const code = errorCode(e);

  if (code !== null && NOT_GCODE.has(code)) {
    return {
      ...notGcode(name, code, errorMessage(e)),
      primary: { label: 'Başka dosya seç', run: actions.pickAnother },
    };
  }

  const line = errorDetailNumber(e, 'line');
  const copy = {
    label: 'Ayrıntıyı kopyala',
    doneLabel: 'Kopyalandı',
    run: () => copyFailureReport(path, e),
  };

  if (code === 'truncated' && line !== null) {
    return {
      kind: 'error',
      title: 'G-code okunamadı',
      body: `Dosya ${integer(line)}. satırda kesilmiş. Aktarma yarıda kalmış olabilir.`,
      chip: `satır ${integer(line)} · beklenmeyen dosya sonu`,
      chipFont: 'sans',
      primary: { label: 'Yeniden dene', run: actions.retry },
      secondary: copy,
    };
  }

  return {
    kind: 'error',
    title: 'G-code okunamadı',
    body: errorText(e),
    chip: name,
    primary: { label: 'Yeniden dene', run: actions.retry },
    secondary: copy,
  };
}

function notGcode(name: string, code: string, message: string): Omit<Alert, 'primary'> {
  const base = { kind: 'error' as const, title: 'Bu dosya desteklenmiyor' };
  if (code === 'model_file') {
    return {
      ...base,
      body: 'SkipFrame yalnızca dilimlenmiş G-code okur. Bıraktığın dosya bir 3D model.',
      chip: `${name} · 3D model`,
      hint: 'Önce slicer’da dilimle',
    };
  }
  if (code === 'no_gcode_in_archive') {
    return {
      ...base,
      body: 'SkipFrame yalnızca dilimlenmiş G-code okur. Bu .3mf bir proje dosyası; içinde dilimlenmiş plaka yok.',
      chip: `${name} · G-code içermiyor`,
      hint: 'Önce slicer’da dilimle',
    };
  }
  if (message.includes('.bgcode')) {
    return {
      ...base,
      body: 'İkili G-code (.bgcode) henüz okunamıyor. Slicer’da düz G-code olarak dışa aktar.',
      chip: `${name} · ikili G-code`,
      hint: 'Düz .gcode olarak kaydet',
    };
  }
  return {
    ...base,
    body: 'SkipFrame yalnızca dilimlenmiş G-code okur: .gcode, .gco, .g ve .gcode.3mf.',
    chip: name,
  };
}

/**
 * The report "Ayrıntıyı kopyala" puts on the clipboard: enough for someone else to tell what
 * happened — the file's name, the code, the line, the slicer, the version — and nothing from
 * inside the file beyond the slicer's own banner.
 */
async function copyFailureReport(path: string, e: unknown): Promise<void> {
  const lines = [`SkipFrame ${await appVersion()} · G-code okunamadı`, `Dosya: ${nameOf(path)}`];
  lines.push(`Kod: ${errorCode(e) ?? 'bilinmiyor'}`);

  const line = errorDetailNumber(e, 'line');
  const read = errorDetailNumber(e, 'layersRead');
  const declared = errorDetailNumber(e, 'layersDeclared');
  if (line !== null) {
    lines.push(
      read !== null && declared !== null
        ? `Satır: ${line} · katman ${read}/${declared}`
        : `Satır: ${line}`,
    );
  }

  const slicer = await slicerBanner(path);
  if (slicer) lines.push(`Slicer: ${slicer}`);
  lines.push(`İleti: ${errorMessage(e)}`);

  await navigator.clipboard.writeText(lines.join('\n'));
}

/** The line in which the slicer names itself, if the file has one. */
async function slicerBanner(path: string): Promise<string | null> {
  try {
    const header = await invoke<string[]>('gcode_header', { path });
    return header.find((l) => /generated by|slicer/i.test(l)) ?? null;
  } catch {
    return null;
  }
}

async function appVersion(): Promise<string> {
  try {
    const { getVersion } = await import('@tauri-apps/api/app');
    return await getVersion();
  } catch {
    return '';
  }
}

/**
 * Opened, but with the fallback reader: the geometry is right and the layer count is inferred.
 */
export function unknownDialectAlert(path: string, layerCount: number): Alert {
  return {
    kind: 'warning',
    title: 'Slicer lehçesi tanınmadı',
    body:
      'Dosya okunuyor ama katman yorumları bilinen bir biçimde değil. Video üretilebilir; ' +
      'katman sayısı tahmini olabilir.',
    chip: `yedek okuyucu · ~${integer(layerCount)} katman`,
    primary: { label: 'Yine de devam et', run: () => {} },
    secondary: {
      label: 'Lehçe bildir',
      run: async () => {
        try {
          await invoke('report_dialect', { path, layers: layerCount });
        } catch (err) {
          notifyError('Bildirim taslağı açılamadı', err);
        }
      },
    },
  };
}

function nameOf(path: string): string {
  return path.split(/[\\/]/).pop() ?? path;
}
