//! Layer 2 of the parser: slicer dialect detection and semantic comment vocabulary.
//!
//! Everything in this module is best-effort. When a file's dialect is unknown, or a known
//! dialect stops emitting the markers we expect, the caller degrades to geometry-only output
//! and records a warning -- it never fails the job.

use crate::ir::FeatureType;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Dialect {
    PrusaSlicer,
    OrcaSlicer,
    BambuStudio,
    Cura,
    /// Creality Print and Creality Slicer: Cura derivatives, same comment vocabulary.
    CrealityPrint,
    #[default]
    Unknown,
}

impl Dialect {
    pub fn name(self) -> &'static str {
        match self {
            Dialect::PrusaSlicer => "PrusaSlicer",
            Dialect::OrcaSlicer => "OrcaSlicer",
            Dialect::BambuStudio => "BambuStudio",
            Dialect::Cura => "Cura",
            Dialect::CrealityPrint => "CrealityPrint",
            Dialect::Unknown => "Unknown",
        }
    }

    /// True when the dialect is known not to emit `;WIDTH:`, so extrusion width has to be
    /// derived from the E delta and the layer height.
    pub fn derives_width(self) -> bool {
        matches!(
            self,
            Dialect::Cura | Dialect::CrealityPrint | Dialect::Unknown
        )
    }

    /// Try to identify the slicer from a single comment body (the text after `;`, trimmed).
    /// Returns the dialect and the version string when the banner carries one.
    pub fn detect(comment: &str) -> Option<(Dialect, Option<String>)> {
        let lower = comment.to_ascii_lowercase();

        // Bambu Studio and Orca both descend from PrusaSlicer and can also emit a
        // "generated by" banner, so the more specific names are tested first.
        let dialect = if lower.contains("bambustudio") || lower.contains("bambu studio") {
            Dialect::BambuStudio
        } else if lower.contains("orcaslicer") || lower.contains("orca slicer") {
            Dialect::OrcaSlicer
        } else if lower.contains("prusaslicer") {
            Dialect::PrusaSlicer
        } else if lower.contains("creality") {
            Dialect::CrealityPrint
        } else if lower.contains("cura_steamengine") || lower.contains("generated with cura") {
            Dialect::Cura
        } else {
            return None;
        };

        Some((dialect, extract_version(comment)))
    }

    /// Does this comment mark the start of a new layer? Cura-style markers carry the index.
    pub fn layer_marker(self, comment: &str) -> Option<LayerMarker> {
        match self {
            Dialect::Cura | Dialect::CrealityPrint => {
                let rest = strip_key(comment, "LAYER")?;
                Some(LayerMarker {
                    index: rest.trim().parse::<u32>().ok(),
                })
            }
            Dialect::BambuStudio => (comment.eq_ignore_ascii_case("CHANGE_LAYER"))
                .then_some(LayerMarker { index: None }),
            Dialect::PrusaSlicer | Dialect::OrcaSlicer => (comment
                .eq_ignore_ascii_case("LAYER_CHANGE"))
            .then_some(LayerMarker { index: None }),
            // Accept any of them when we do not know the dialect -- costs one comparison and
            // rescues re-exported or post-processed files.
            Dialect::Unknown => {
                if comment.eq_ignore_ascii_case("LAYER_CHANGE")
                    || comment.eq_ignore_ascii_case("CHANGE_LAYER")
                {
                    Some(LayerMarker { index: None })
                } else {
                    strip_key(comment, "LAYER").map(|rest| LayerMarker {
                        index: rest.trim().parse::<u32>().ok(),
                    })
                }
            }
        }
    }

    /// Declared Z of the layer that is starting, if the dialect announces it separately.
    pub fn layer_z(self, comment: &str) -> Option<f32> {
        let rest = strip_key(comment, "Z_HEIGHT")
            .or_else(|| strip_key(comment, "Z"))
            .or_else(|| strip_key(comment, "LAYER_Z"))?;
        rest.trim().parse::<f32>().ok()
    }

    /// Feature/role marker. All known dialects use either `TYPE:` or `FEATURE:`.
    pub fn feature_marker(self, comment: &str) -> Option<FeatureType> {
        let rest = strip_key(comment, "TYPE").or_else(|| strip_key(comment, "FEATURE"))?;
        Some(feature_from_name(rest.trim()))
    }

    /// Declared extrusion width, `;WIDTH:0.45`.
    pub fn width_marker(self, comment: &str) -> Option<f32> {
        strip_key(comment, "WIDTH")?.trim().parse::<f32>().ok()
    }
}

#[derive(Debug, Clone, Copy)]
pub struct LayerMarker {
    /// Present for Cura-style `;LAYER:n`; `None` when the dialect only signals "next layer".
    pub index: Option<u32>,
}

/// `strip_key("TYPE:WALL-OUTER", "TYPE")` -> `Some("WALL-OUTER")`. Case-insensitive on the key,
/// tolerant of the space some dialects put before the colon value.
fn strip_key<'a>(comment: &'a str, key: &str) -> Option<&'a str> {
    let bytes = comment.as_bytes();
    if bytes.len() <= key.len() || !comment[..key.len()].eq_ignore_ascii_case(key) {
        return None;
    }
    let rest = &comment[key.len()..];
    rest.strip_prefix(':')
}

/// One table for every dialect: the vocabularies do not collide, so a single match keeps the
/// mapping in one reviewable place.
fn feature_from_name(name: &str) -> FeatureType {
    let n = name.trim().to_ascii_lowercase();
    match n.as_str() {
        // PrusaSlicer / Orca / Bambu
        "external perimeter" | "outer wall" | "overhang perimeter" | "overhang wall" => {
            FeatureType::OuterWall
        }
        "perimeter" | "inner wall" | "internal perimeter" => FeatureType::InnerWall,
        "solid infill" | "internal solid infill" | "bottom surface" => FeatureType::SolidInfill,
        "internal infill" | "sparse infill" | "gap fill" | "gap infill" => {
            FeatureType::SparseInfill
        }
        "top solid infill" | "top surface" => FeatureType::TopSurface,
        "bridge infill" | "bridge" | "internal bridge infill" => FeatureType::Bridge,
        "support material" | "support material interface" | "support" | "support interface" => {
            FeatureType::Support
        }
        "skirt/brim" | "skirt" | "brim" | "prime tower" | "wipe tower" => FeatureType::SkirtBrim,

        // Cura / Creality Print
        "wall-outer" => FeatureType::OuterWall,
        "wall-inner" => FeatureType::InnerWall,
        "skin" => FeatureType::SolidInfill,
        "fill" => FeatureType::SparseInfill,
        "support-interface" => FeatureType::Support,
        "prime-tower" => FeatureType::SkirtBrim,

        _ => {
            if n.starts_with("support") {
                FeatureType::Support
            } else if n.starts_with("wall") || n.contains("perimeter") {
                FeatureType::InnerWall
            } else if n.contains("infill") || n.contains("fill") {
                FeatureType::SparseInfill
            } else {
                FeatureType::Unknown
            }
        }
    }
}

/// Pull a version token out of a banner such as `generated by PrusaSlicer 2.8.1+win64`.
fn extract_version(comment: &str) -> Option<String> {
    comment
        .split_whitespace()
        .find(|tok| {
            let t = tok.trim_start_matches('v');
            t.starts_with(|c: char| c.is_ascii_digit()) && t.contains('.')
        })
        .map(|t| t.trim_start_matches('v').to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_every_supported_banner() {
        let cases = [
            (
                "generated by PrusaSlicer 2.8.1+win64 on 2024-01-01",
                Dialect::PrusaSlicer,
            ),
            (
                "generated by OrcaSlicer 2.1.1 on 2024-05-05",
                Dialect::OrcaSlicer,
            ),
            ("generated by BambuStudio 1.9.0.50", Dialect::BambuStudio),
            ("Generated with Cura_SteamEngine 5.7.0", Dialect::Cura),
            (
                "Generated with Creality Print 5.1.0",
                Dialect::CrealityPrint,
            ),
        ];
        for (banner, want) in cases {
            let (got, _) = Dialect::detect(banner).expect(banner);
            assert_eq!(got, want, "{banner}");
        }
        assert!(Dialect::detect("just a regular comment").is_none());
    }

    #[test]
    fn reads_layer_markers_per_dialect() {
        assert!(Dialect::PrusaSlicer.layer_marker("LAYER_CHANGE").is_some());
        assert!(Dialect::BambuStudio.layer_marker("CHANGE_LAYER").is_some());
        let m = Dialect::Cura
            .layer_marker("LAYER:42")
            .expect("cura layer marker");
        assert_eq!(m.index, Some(42));
        assert!(Dialect::Cura.layer_marker("LAYER_COUNT:570").is_none());
    }

    #[test]
    fn maps_feature_vocabularies_onto_one_enum() {
        assert_eq!(
            Dialect::PrusaSlicer.feature_marker("TYPE:External perimeter"),
            Some(FeatureType::OuterWall)
        );
        assert_eq!(
            Dialect::BambuStudio.feature_marker("FEATURE: Outer wall"),
            Some(FeatureType::OuterWall)
        );
        assert_eq!(
            Dialect::Cura.feature_marker("TYPE:WALL-OUTER"),
            Some(FeatureType::OuterWall)
        );
        assert_eq!(
            Dialect::Cura.feature_marker("TYPE:FILL"),
            Some(FeatureType::SparseInfill)
        );
        assert_eq!(
            Dialect::OrcaSlicer.feature_marker("TYPE:Something New"),
            Some(FeatureType::Unknown)
        );
    }

    #[test]
    fn reads_width_and_z() {
        assert_eq!(Dialect::PrusaSlicer.width_marker("WIDTH:0.45"), Some(0.45));
        assert_eq!(Dialect::BambuStudio.layer_z("Z_HEIGHT: 0.6"), Some(0.6));
        assert_eq!(Dialect::PrusaSlicer.layer_z("Z:0.2"), Some(0.2));
    }
}
