//! The comment block at the top of a G-code file, as a person would read it.
//!
//! Used when a user reports a slicer SkipFrame does not recognise: the header is where a slicer
//! names itself, its version and the printer, and it is the only part of the file such a report
//! should carry. No geometry, no thumbnail, nothing past the first line of G-code.

use std::io::BufRead;
use std::path::Path;

use crate::container;
use crate::error::Result;

/// Lines kept. Enough for the banner and the settings a slicer puts first.
pub const MAX_LINES: usize = 20;

/// A comment longer than this is shortened; nobody needs a full config string in a bug report.
const MAX_LINE_CHARS: usize = 160;

/// Give up looking for the header after this many lines of anything.
const SCAN_LIMIT: usize = 2000;

/// The readable header comments of the file at `path`, first plate for a `.gcode.3mf`.
pub fn read_header(path: &Path, max_lines: usize) -> Result<Vec<String>> {
    Ok(container::with_reader(path, None, |r| header_comments(r, max_lines))?.0)
}

pub fn header_comments(reader: &mut dyn BufRead, max_lines: usize) -> Result<Vec<String>> {
    let mut out = Vec::new();
    let mut line = String::new();

    for _ in 0..SCAN_LIMIT {
        line.clear();
        if reader.read_line(&mut line)? == 0 {
            break;
        }
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let Some(comment) = trimmed.strip_prefix(';') else {
            // The first real command ends the header.
            break;
        };
        let comment = comment.trim();

        // A thumbnail block is a picture of the model as base64: not header, not wanted.
        let lower = comment.to_ascii_lowercase();
        if lower.contains("thumbnail_block_start") || lower.starts_with("thumbnail begin") {
            break;
        }
        if comment.is_empty() || looks_like_base64(comment) {
            continue;
        }

        let mut kept: String = comment.chars().take(MAX_LINE_CHARS).collect();
        if comment.chars().count() > MAX_LINE_CHARS {
            kept.push('…');
        }
        out.push(kept);
        if out.len() >= max_lines {
            break;
        }
    }
    Ok(out)
}

/// One long unbroken run of base64 alphabet — thumbnail data that slipped outside its block.
fn looks_like_base64(s: &str) -> bool {
    s.len() > 40
        && !s.contains(' ')
        && s.bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'=')
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    fn header(src: &str, max: usize) -> Vec<String> {
        header_comments(&mut Cursor::new(src.as_bytes().to_vec()), max).unwrap()
    }

    /// The top of the real OrcaSlicer file, thumbnail and all.
    const ORCA: &str = "; HEADER_BLOCK_START\n\
        ; generated by OrcaSlicer 2.4.2 on 2026-09-08 at 12:11:08\n\
        ; total layer number: 568\n\
        ; filament_diameter: 1.75\n\
        ; HEADER_BLOCK_END\n\
        \n\
        ; THUMBNAIL_BLOCK_START\n\
        ;\n\
        ; thumbnail begin 140x110 7672\n\
        ; iVBORw0KGgoAAAANSUhEUgAAAIwAAABuCAYAAAD1TPu3AAAWQUlEQVR4Ae2diVaVV5qGTxvnIRpBQG\n\
        G1 X10 Y10\n";

    #[test]
    fn keeps_the_banner_and_stops_at_the_thumbnail() {
        assert_eq!(
            header(ORCA, MAX_LINES),
            vec![
                "HEADER_BLOCK_START",
                "generated by OrcaSlicer 2.4.2 on 2026-09-08 at 12:11:08",
                "total layer number: 568",
                "filament_diameter: 1.75",
                "HEADER_BLOCK_END",
            ]
        );
    }

    #[test]
    fn never_carries_geometry_or_stray_base64() {
        let src = "; generated by Foo 1.0\n\
            ; iVBORw0KGgoAAAANSUhEUgAAAIwAAABuCAYAAAD1TPu3AAAWQUlEQVR4Ae2\n\
            G1 X1 Y1 E1\n\
            ; a comment after the first move\n";
        assert_eq!(header(src, MAX_LINES), vec!["generated by Foo 1.0"]);
    }

    #[test]
    fn caps_how_much_it_keeps() {
        let many: String = (0..50).map(|i| format!("; setting_{i} = {i}\n")).collect();
        assert_eq!(header(&many, MAX_LINES).len(), MAX_LINES);

        let long = format!("; {}\n", "x ".repeat(200));
        let kept = &header(&long, MAX_LINES)[0];
        assert!(kept.ends_with('…') && kept.chars().count() == MAX_LINE_CHARS + 1);
    }
}
